# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
  
    environment: aws
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        # region must match your ECR repository
        region: us-west-1
        # Provide AWS credentials via GitHub secrets
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build, tag, and push Docker image
      run: |
        # Update with your AWS account ID and region
        ECR_REGISTRY="424579921836.dkr.ecr.us-west-1.amazonaws.com"
        ECR_REPOSITORY="counter-service"
        # Build Docker image
        docker build -t $ECR_REPOSITORY:latest .
        # Tag Docker image
        docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
        # Push to ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
