# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    
    environment: aws
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      id: login-acr

    - name: Build, tag, and push Docker image
      run: |
        # Update with your AWS account ID and region
        ECR_REGISTRY="424579921836.dkr.ecr.us-west-1.amazonaws.com"
        ECR_REPOSITORY="counter-service"
        # Build Docker image
        docker build -t $ECR_REPOSITORY:latest .
        # Tag Docker image
        docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
        # Push to ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -sSL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Install AWS IAM Authenticator
      run: |
        curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.24.9/2023-03-17/bin/linux/amd64/aws-iam-authenticator
        chmod +x ./aws-iam-authenticator
        sudo mv aws-iam-authenticator /usr/local/bin/

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}
        
    - name: Create K8s Service
      run: |
        cat <<EOF > counter-service-service.yaml
        apiVersion: v1
        kind: Service
        metadata:
          name: counter-service
        spec:
          type: LoadBalancer
          selector:
            app: counter-service
          ports:
            - protocol: TCP
              port: 443
              targetPort: 8080
        EOF
        kubectl apply -f counter-service-service.yaml
        
    - name: Deploy K8s resources
      run: |
        cat <<EOF > counter-service-deployment.yaml
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: counter-service-deployment
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: counter-service
          template:
            metadata:
              labels:
                app: counter-service
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: eks.amazonaws.com/nodegroup
                        operator: In
                        values:
                        - "node-group-2-*" # Replace with specific node group patterns if needed
              containers:
              - name: counter-service-container
                image: 424579921836.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/counter-service:latest
                ports:
                - containerPort: 8080
                securityContext:
                  runAsUser: 1000
                  runAsGroup: 1000
                  runAsNonRoot: true
        EOF
        kubectl apply -f counter-service-deployment.yaml

    - name: Deploy to EKS
      run: |
        kubectl set image deployment/counter-service-deployment counter-service-container=424579921836.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/counter-service:latest
        kubectl rollout status deployment/counter-service-deployment
